In [4]:
import numpy as np
v1=np.array([1,2,3,])
v2=np.array([4,5,6])
print(v1,v2)
mag_v2=np.linalg.norm(v2)
print(mag_v2)


[1 2 3] [4 5 6]
8.774964387392123


In [21]:
#lets make some matrixes
import numpy as np
a=np.array([[1,2,3],[4,5,8,],[7,8,17]])
b=np.array([[7,8,9],[10,11,12],[13,14,15]])
print(a)
print(b)
print(a@b)
d=np.array([5,11,13])
c=np.linalg.solve(a,d)
print(c)

#lets find eiven values. 
H=np.array([[2,1],[1,2]])
eigenvalues,eigenvectors=np.linalg.eig(H)
print("eigenvalues:",eigenvalues)
print("eigenvectors:",eigenvectors)
H_inv=np.linalg.inv(H)
print("inverse of H:",H_inv)
#verify they work 
final_return=np.dot(H,H_inv)
print(final_return)

[[ 1  2  3]
 [ 4  5  8]
 [ 7  8 17]]
[[ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[ 66  72  78]
 [182 199 216]
 [350 382 414]]
[-0.66666667  4.33333333 -1.        ]
eigenvalues: [3. 1.]
eigenvectors: [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
inverse of H: [[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]
[[1. 0.]
 [0. 1.]]


In [39]:
#hard way 

import numpy as np

def gaussian_elimination(A, b):
    n = len(b)

    # Forward elimination
    for i in range(n):
        # Pivoting
        max_row = max(range(i, n), key=lambda x: abs(A[x][i]))
        A[i], A[max_row] = A[max_row], A[i]
        b[i], b[max_row] = b[max_row], b[i]

        # Make the rows below this one 0 in current column
        for j in range(i + 1, n):
            ratio = A[j][i] / A[i][i]
            A[j] = [A[j][k] - ratio * A[i][k] for k in range(n)]
            b[j] -= ratio * b[i]

    # Backward substitution
    x = [0] * n
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - sum(A[i][j] * x[j] for j in range(i + 1, n))) / A[i][i]

    return x

In [35]:
#easy way


A = [[3, 2, -4], [2, 3, 3], [5, -3, 1]]
b = [3, 15, 14]
c=[[2,3,-1],[4,-2,2],[-2,1,2]]
d=[5,6,-1]
solution = gaussian_elimination(A, b)
solutions= gaussian_elimination(c,d)
print(f"Solution: {solution}")
print(solutions)

Solution: [2.9999999999999996, 0.9999999999999996, 2.0]
[1.5833333333333333, 0.8333333333333333, 0.6666666666666666]


In [37]:
#LU decomposition hard way

import numpy as np

def lu_decomposition(A):
    n = len(A)
    L = np.eye(n)                      # Initialize L as identity matrix
    U = np.array(A, dtype=float)       # Copy of A to avoid modifying original

    for i in range(n):
        # Eliminate elements below the pivot (U[i, i])
        for j in range(i + 1, n):

            if U[i, i] == 0:
                raise ValueError("Zero pivot encountered. LU decomposition cannot proceed.")

            factor = U[j, i] / U[i, i]   # Multiplier for row operation
            L[j, i] = factor             # Store multiplier in L

            # Update the rows of U
            for k in range(i, n):
                U[j, k] -= factor * U[i, k]

    return L, U


# Example usage
A = np.array([[2, 3, 1],
              [4, 7, -1],
              [-2, 1, 2]])

L, U = lu_decomposition(A)

print("Matrix A:\n", A)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)


Matrix A:
 [[ 2  3  1]
 [ 4  7 -1]
 [-2  1  2]]
Lower Triangular Matrix L:
 [[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  4.  1.]]
Upper Triangular Matrix U:
 [[ 2.  3.  1.]
 [ 0.  1. -3.]
 [ 0.  0. 15.]]


In [38]:
#easy way
import numpy as np
from scipy.linalg import lu
# Example matrix
A = np.array([[2, 3, 1],
[4, 7, -1],
[-2, 1, 2]])

# Perform LU Decomposition
P, L, U = lu(A)
print("Matrix A:\n", A)
print("Permutation Matrix P:\n", P)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)


Matrix A:
 [[ 2  3  1]
 [ 4  7 -1]
 [-2  1  2]]
Permutation Matrix P:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
Lower Triangular Matrix L:
 [[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.5        -0.11111111  1.        ]]
Upper Triangular Matrix U:
 [[ 4.          7.         -1.        ]
 [ 0.          4.5         1.5       ]
 [ 0.          0.          1.66666667]]


In [ ]:
#Iterative methods put a guess, compare first guess to new guess and see if were getting mroe accurate until relative error is 
#tolerable