# This is part A

In [10]:
import numpy as np
import math
import time
import matplotlib.pyplot as plt 

#this is part A

A = np.array([
	[0.582745, 0.48	, 0.10	, 0.  	, 0.  	], 
 [0.48	, 1.044129, 0.46	, 0.10	, 0.  	],
 [0.10	, 0.46	, 1.10431 , 0.44	, 0.10	],
 [0.  	, 0.10	, 0.44	, 0.963889, 0.42	],
 [0.  	, 0.  	, 0.10	, 0.42	, 0.522565]], dtype=float)
b = np.array([1.162745, 2.084129, 2.20431 , 1.923889, 1.042565], dtype=float)

x0 = np.array([0, 0, 0,0,0],dtype=float)
tolerances = [ 1e-6]
max_iterations = 100

def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    errors = []
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        error = np.linalg.norm(x_new - x, ord=np.inf)
        errors.append(error)
        if error < tol:
            return x_new, k, errors
        x = x_new
    return x, max_iterations, errors

def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    errors = []
    for k in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        error = np.linalg.norm(x_new - x, ord=np.inf)
        errors.append(error)
        if error < tol:
            return x_new, k, errors
        x = x_new
    return x, max_iterations, errors

for tol in tolerances:
    print(f"Tolerance: {tol}")

    start = time.time()
    jacobi_solution, jacobi_iterations, jacobi_errors = jacobi(A, b, x0, tol, max_iterations)
    jacobi_time = time.time() - start

    start = time.time()
    gs_solution, gs_iterations, gs_errors = gauss_seidel(A, b, x0, tol, max_iterations)
    gs_time = time.time() - start
    
    print(f"  Jacobi Solution: {jacobi_solution}")
    print(f"  Jacobi Iterations: {jacobi_iterations}")
    print(f"  Jacobi Time: {jacobi_time:.6f} seconds")
    print(f"  Gauss-Seidel Solution: {gs_solution}")
    print(f"  Gauss-Seidel Iterations: {gs_iterations}")
    print(f"  Gauss-Seidel Time: {gs_time:.6f} seconds")
    print()

    

Tolerance: 1e-06
  Jacobi Solution: [0.34253948 0.34219824 0.34215212 0.34233398 0.34277892]
  Jacobi Iterations: 100
  Jacobi Time: 0.006346 seconds
  Gauss-Seidel Solution: [0.99999926 1.00000045 0.99999989 0.99999997 1.00000005]
  Gauss-Seidel Iterations: 20
  Gauss-Seidel Time: 0.001043 seconds



# This is part

In [13]:
import numpy as np
import math
import time
import matplotlib.pyplot as plt

A = np.array([[1, 	1], [1, 1.0001]])
b = np.array([1, 1])




x0 = np.array([0, 0, 0,0,0], dtype =float)
tolerances = [ 1e-6]
max_iterations = 100

def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    errors = []
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        error = np.linalg.norm(x_new - x, ord=np.inf)
        errors.append(error)
        if error < tol:
            return x_new, k, errors
        x = x_new
    return x, max_iterations, errors

def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    errors = []
    for k in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        error = np.linalg.norm(x_new - x, ord=np.inf)
        errors.append(error)
        if error < tol:
            return x_new, k, errors
        x = x_new
    return x, max_iterations, errors

for tol in tolerances:
    print(f"Tolerance: {tol}")

    start = time.time()
    jacobi_solution, jacobi_iterations, jacobi_errors = jacobi(A, b, x0, tol, max_iterations)
    jacobi_time = time.time() - start

    start = time.time()
    gs_solution, gs_iterations, gs_errors = gauss_seidel(A, b, x0, tol, max_iterations)
    gs_time = time.time() - start
    
    print(f"  Jacobi Solution: {jacobi_solution}")
    print(f"  Jacobi Iterations: {jacobi_iterations}")
    print(f"  Jacobi Time: {jacobi_time:.6f} seconds")
    print(f"  Gauss-Seidel Solution: {gs_solution}")
    print(f"  Gauss-Seidel Iterations: {gs_iterations}")
    print(f"  Gauss-Seidel Time: {gs_time:.6f} seconds")
    print()


Tolerance: 1e-06
  Jacobi Solution: [0.00498727 0.         0.         0.         0.        ]
  Jacobi Iterations: 100
  Jacobi Time: 0.004823 seconds
  Gauss-Seidel Solution: [1. 0. 0. 0. 0.]
  Gauss-Seidel Iterations: 1
  Gauss-Seidel Time: 0.000118 seconds



# this is part c 

In [14]:
import numpy as np
import math
import time
import matplotlib.pyplot as plt

A = np.array([[1, 	1], [1, 1.0001]])
b = np.array([1, 1.0001])

x0 = np.array([0, 0], dtype =float)
tolerances = [ 1e-6]
max_iterations = 100

def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    errors = []
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        error = np.linalg.norm(x_new - x, ord=np.inf)
        errors.append(error)
        if error < tol:
            return x_new, k, errors
        x = x_new
    return x, max_iterations, errors

def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    errors = []
    for k in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        error = np.linalg.norm(x_new - x, ord=np.inf)
        errors.append(error)
        if error < tol:
            return x_new, k, errors
        x = x_new
    return x, max_iterations, errors

for tol in tolerances:
    print(f"Tolerance: {tol}")

    start = time.time()
    jacobi_solution, jacobi_iterations, jacobi_errors = jacobi(A, b, x0, tol, max_iterations)
    jacobi_time = time.time() - start

    start = time.time()
    gs_solution, gs_iterations, gs_errors = gauss_seidel(A, b, x0, tol, max_iterations)
    gs_time = time.time() - start
    
    print(f"  Jacobi Solution: {jacobi_solution}")
    print(f"  Jacobi Iterations: {jacobi_iterations}")
    print(f"  Jacobi Time: {jacobi_time:.6f} seconds")
    print(f"  Gauss-Seidel Solution: {gs_solution}")
    print(f"  Gauss-Seidel Iterations: {gs_iterations}")
    print(f"  Gauss-Seidel Time: {gs_time:.6f} seconds")
    print()
#both do not converge with just a small decimal

Tolerance: 1e-06
  Jacobi Solution: [0.         0.00498727]
  Jacobi Iterations: 100
  Jacobi Time: 0.005949 seconds
  Gauss-Seidel Solution: [0.99014933 0.00994967]
  Gauss-Seidel Iterations: 100
  Gauss-Seidel Time: 0.003199 seconds



# This is part D

In [22]:
import numpy as np
import math
import time 
import matplotlib.pyplot as plt

A = np.array([
	[0.582745, 0.48	, 0.10	, 0.  	, 0.  	], 
 [0.48	, 1.044129, 0.46	, 0.10	, 0.  	],
 [0.10	, 0.46	, 1.10431 , 0.44	, 0.10	],
 [0.  	, 0.10	, 0.44	, 0.963889, 0.42	],
 [0.  	, 0.  	, 0.10	, 0.42	, 0.522565]], dtype=float)


#try with example from part CH6B

def is_diagonally_dominant(A):
    n = len(A)
    for i in range(n):
        diagonal = abs(A[i][i])
        off_diagonal = sum(abs(A[i][j]) for j in range(n) if j != i)
        if diagonal < off_diagonal:
            return False
    return True

print(A)
print(f"Is the matrix diagonally dominant? {is_diagonally_dominant(A)}")

[[0.582745 0.48     0.1      0.       0.      ]
 [0.48     1.044129 0.46     0.1      0.      ]
 [0.1      0.46     1.10431  0.44     0.1     ]
 [0.       0.1      0.44     0.963889 0.42    ]
 [0.       0.       0.1      0.42     0.522565]]
Is the matrix diagonally dominant? True


# We see it says false so it checks out

In [21]:
import numpy as np 

A = np.array([[1, 2, 3, 0, 0],
              [2, 1, 2, 3, 0],
              [3, 2, 1, 2, 3],
              [0, 3, 2, 1, 2],
              [0, 0, 3, 2, 1]])

def is_diagonally_dominant(A):
    n = len(A)
    for i in range(n):
        diagonal = abs(A[i][i])
        off_diagonal = sum(abs(A[i][j]) for j in range(n) if j != i)
        if diagonal < off_diagonal:
            return False
    return True

print(A)
print(f"Is the matrix diagonally dominant? {is_diagonally_dominant(A)}")

[[1 2 3 0 0]
 [2 1 2 3 0]
 [3 2 1 2 3]
 [0 3 2 1 2]
 [0 0 3 2 1]]
Is the matrix diagonally dominant? False
